### PR TITLE
Fixed the issue of overriding filetags for existing file

### LINKED ISSUE #61: Currently curl is overriding the tags of existing files
This feature is enhance curl to not modifying the tags of existing files

### PR DESCRIPTION
**Pull request by HarithaIBM**
This PR introduces several fixes and enhancements to the Curl port for z/OS, primarily focusing on
  character encoding support and the stabilization of the test suite.

  Summary of Changes
   * New doc: Added add-download-encoding.patch and add-upload-encoding.patch doc to integrate
     these options into the tool's parameter parsing and transfer logic.
   * File Handling: Updated tool_cb_wrt.c.patch to ensure that downloaded data is correctly handled when
     being written to z/OS UNIX existing files.

  **Test Suite Stabilization (--libcurl Generation)**
   * Environment Isolation: Fixed 11 test cases (1400-1407, 1420, 1465, 1481) that were failing due to
     platform-specific defaults being captured in the generated C code.
   * Verification Logic: Applied patches to test data (e.g., test1400.patch, data1400.c.patch) to strip
     environment-dependent options like CURLOPT_VERBOSE and CURLOPT_CAINFO during comparison. This ensures
     behavioral consistency across different z/OS build environments.

 **Infrastructure & Tooling**
   * Test Runner Updates: Modified runtests.pl.patch to improve system feature detection for z/OS
     (identifying as zos or openedition), allowing for better conditional test execution.
   * New Test Coverage: Added several new test cases (test4002.patch through test4005.patch) to verify the
     new encoding functionality in a controlled environment.

  Impact
  These changes ensure that Curl on z/OS can reliably transfer files between different character sets and
  that the automated test suite can accurately validate the tool's behavior without being distracted by
  local environment configurations.

### CODE REVIEW

File: stable-patches/src/tool_cb_wrt.c.patch [hunk 1]
```diff
@@ -66,11 +66,13 @@ index 1b76565..5aa1892 100644
 +  
 +  /* Handle CCSID tagging (backward compatibility with --tag) */
 +  if(config->local_ccsid == 0 && outs->bytes == 0 && !config->resume_from && !getenv("_ENCODE_FILE_NEW")) {
-+    int ccsid = __guess_ue(buffer, bytes, NULL, 0);
-+    if(ccsid == 65535)
-+      __chgfdccsid(fileno(outs->stream), FT_BINARY);
-+    else
-+      __chgfdccsid(fileno(outs->stream), ccsid);
++    if(__getfdccsid(fileno(outs->stream)) == 0) {
```
[the remark this answers is not in the document]
Comment (HarithaIBM) [reply stable-patches/src/tool_cb_wrt.c.patch]: Resolved

**Comment by HarithaIBM** [comment]
1. Why CURLOPT_VERBOSE and CURLOPT_CAINFO are removed/stripped:
       * Context: These changes occur in tests (like test1406) that verify the --libcurl
         feature, which generates C code from a curl command line.
       * Reason: CURLOPT_VERBOSE and CURLOPT_CAINFO are stripped to make the generated C code
         deterministic and portable.
           * CURLOPT_CAINFO often contains an absolute path to a certificate bundle, which
             varies by system.
           * CURLOPT_VERBOSE is removed to prevent the generated code from being
             unnecessarily noisy when compiled and run, as well as to avoid discrepancies if
             the test runner itself has different default verbosity settings.
       * Where are they tested?
           * CURLOPT_VERBOSE: Tested in numerous integration and unit tests where actual
             debug output is required. For example, tests/libtest/cli_ftp_upload.c,
             cli_h2_pausing.c, etc., explicitly set this option to verify protocol
2. Why -T, --upload-file is removed from data1461.txt:
       * Context: data1461.txt tests the output of curl -h (short help).
       * Reason: The patch in stable-patches/src/tool_listhelp.c.patch [removed](https://github.com/zopencommunity/curlport/commit/27e9666bf618d4741b2f1b36d8418ad1799646b3) the
         CURLHELP_IMPORTANT flag from the --upload-file option. Since curl -h only displays
         options marked as "important," it no longer appears in that specific output.
       * Which test is testing upload-file?
           * Functionality: Many tests still use -T for actual uploads, such as test10,
             test1001, test1002, test1291, and test1326.
           * Help Text: It still appears in the full help (curl --help), which is tested by
             other files (likely test1139 or similar, depending on the version's help
             categorization).

File: stable-patches/src/tool_cb_wrt.c.patch [hunk 2]
```diff
@@ -66,11 +66,13 @@ index 1b76565..5aa1892 100644
 +  
 +  /* Handle CCSID tagging (backward compatibility with --tag) */
 +  if(config->local_ccsid == 0 && outs->bytes == 0 && !config->resume_from && !getenv("_ENCODE_FILE_NEW")) {
-+    int ccsid = __guess_ue(buffer, bytes, NULL, 0);
-+    if(ccsid == 65535)
-+      __chgfdccsid(fileno(outs->stream), FT_BINARY);
-+    else
-+      __chgfdccsid(fileno(outs->stream), ccsid);
++    if(__getfdccsid(fileno(outs->stream)) <= 0) {
```
Comment (IgorTodorovskiIBM) [inline stable-patches/src/tool_cb_wrt.c.patch:83]: I see, so you are checking if a file is untagged to determine if it exists? 
That should be ok I think, but it might change an untagged file to a tagged file

Comment (HarithaIBM) [reply stable-patches/src/tool_cb_wrt.c.patch:83]: Thank you Igor. Yes , it will tag the existing untagged files as well. Adding logic to distinguish that and apply only for new files.

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM
